name: Basic Workflow

on:
  workflow_dispatch: 
     inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Person to greet"
        # Default value if no value is explicitly provided
        default: "World"
        # Input has to be provided for the workflow to run
        required: true
        # Input Type (string, choice, boolean)
        type: string

jobs:
  greet:
    name: "Greetings, Program!"
    runs-on: ubuntu-latest
    steps:
      # Runs command(s) using the runners shell and gets context from the github object
      - name: Send greeting
        run: |
          echo "Hello ${{ github.event.inputs.name }}" 
          echo "GITHUB CONTEXT: ${{ toJson(github) }}"
